// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    owner_id,
    name,
    description,
    config,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, owner_id, name, description, config, status, created_at, updated_at
`

type CreateAgentParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Config      []byte      `json:"config"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.Status,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, owner_id, name, description, config, status, created_at, updated_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsByOwner = `-- name: ListAgentsByOwner :many
SELECT id, owner_id, name, description, config, status, created_at, updated_at FROM agents 
WHERE owner_id = $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type ListAgentsByOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListAgentsByOwner(ctx context.Context, arg ListAgentsByOwnerParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByStatus = `-- name: ListAgentsByStatus :many
SELECT id, owner_id, name, description, config, status, created_at, updated_at FROM agents 
WHERE owner_id = $1 AND status = $2
ORDER BY created_at DESC 
LIMIT $3 OFFSET $4
`

type ListAgentsByStatusParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Status  string      `json:"status"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListAgentsByStatus(ctx context.Context, arg ListAgentsByStatusParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByStatus,
		arg.OwnerID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET
    name = $2,
    description = $3,
    config = $4,
    status = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, name, description, config, status, created_at, updated_at
`

type UpdateAgentParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Config      []byte      `json:"config"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.Status,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
