// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLLMAttachment = `-- name: CreateLLMAttachment :one
INSERT INTO llm_attachments (
    agent_id,
    provider_id,
    layer,
    priority,
    config
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, agent_id, provider_id, layer, priority, config, created_at
`

type CreateLLMAttachmentParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	ProviderID pgtype.UUID `json:"provider_id"`
	Layer      string      `json:"layer"`
	Priority   int32       `json:"priority"`
	Config     []byte      `json:"config"`
}

func (q *Queries) CreateLLMAttachment(ctx context.Context, arg CreateLLMAttachmentParams) (LlmAttachment, error) {
	row := q.db.QueryRow(ctx, createLLMAttachment,
		arg.AgentID,
		arg.ProviderID,
		arg.Layer,
		arg.Priority,
		arg.Config,
	)
	var i LlmAttachment
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ProviderID,
		&i.Layer,
		&i.Priority,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const createLLMProvider = `-- name: CreateLLMProvider :one
INSERT INTO llm_providers (
    owner_id,
    name,
    provider_type,
    api_key_encrypted,
    base_url,
    model,
    config
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING id, owner_id, name, provider_type, api_key_encrypted, base_url, model, config, created_at, updated_at
`

type CreateLLMProviderParams struct {
	OwnerID         pgtype.UUID `json:"owner_id"`
	Name            string      `json:"name"`
	ProviderType    string      `json:"provider_type"`
	ApiKeyEncrypted pgtype.Text `json:"api_key_encrypted"`
	BaseUrl         pgtype.Text `json:"base_url"`
	Model           pgtype.Text `json:"model"`
	Config          []byte      `json:"config"`
}

func (q *Queries) CreateLLMProvider(ctx context.Context, arg CreateLLMProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, createLLMProvider,
		arg.OwnerID,
		arg.Name,
		arg.ProviderType,
		arg.ApiKeyEncrypted,
		arg.BaseUrl,
		arg.Model,
		arg.Config,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ProviderType,
		&i.ApiKeyEncrypted,
		&i.BaseUrl,
		&i.Model,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLLMAttachment = `-- name: DeleteLLMAttachment :exec
DELETE FROM llm_attachments WHERE id = $1
`

func (q *Queries) DeleteLLMAttachment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLLMAttachment, id)
	return err
}

const deleteLLMProvider = `-- name: DeleteLLMProvider :exec
DELETE FROM llm_providers WHERE id = $1
`

func (q *Queries) DeleteLLMProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLLMProvider, id)
	return err
}

const getLLMProviderByID = `-- name: GetLLMProviderByID :one
SELECT id, owner_id, name, provider_type, api_key_encrypted, base_url, model, config, created_at, updated_at FROM llm_providers WHERE id = $1
`

func (q *Queries) GetLLMProviderByID(ctx context.Context, id pgtype.UUID) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, getLLMProviderByID, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ProviderType,
		&i.ApiKeyEncrypted,
		&i.BaseUrl,
		&i.Model,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLLMAttachmentsByAgent = `-- name: ListLLMAttachmentsByAgent :many
SELECT id, agent_id, provider_id, layer, priority, config, created_at FROM llm_attachments 
WHERE agent_id = $1 
ORDER BY priority DESC
`

func (q *Queries) ListLLMAttachmentsByAgent(ctx context.Context, agentID pgtype.UUID) ([]LlmAttachment, error) {
	rows, err := q.db.Query(ctx, listLLMAttachmentsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmAttachment
	for rows.Next() {
		var i LlmAttachment
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ProviderID,
			&i.Layer,
			&i.Priority,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMProvidersByOwner = `-- name: ListLLMProvidersByOwner :many
SELECT id, owner_id, name, provider_type, api_key_encrypted, base_url, model, config, created_at, updated_at FROM llm_providers 
WHERE owner_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) ListLLMProvidersByOwner(ctx context.Context, ownerID pgtype.UUID) ([]LlmProvider, error) {
	rows, err := q.db.Query(ctx, listLLMProvidersByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmProvider
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.ProviderType,
			&i.ApiKeyEncrypted,
			&i.BaseUrl,
			&i.Model,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLLMProvider = `-- name: UpdateLLMProvider :one
UPDATE llm_providers SET
    name = $2,
    provider_type = $3,
    api_key_encrypted = $4,
    base_url = $5,
    model = $6,
    config = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, name, provider_type, api_key_encrypted, base_url, model, config, created_at, updated_at
`

type UpdateLLMProviderParams struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	ProviderType    string      `json:"provider_type"`
	ApiKeyEncrypted pgtype.Text `json:"api_key_encrypted"`
	BaseUrl         pgtype.Text `json:"base_url"`
	Model           pgtype.Text `json:"model"`
	Config          []byte      `json:"config"`
}

func (q *Queries) UpdateLLMProvider(ctx context.Context, arg UpdateLLMProviderParams) (LlmProvider, error) {
	row := q.db.QueryRow(ctx, updateLLMProvider,
		arg.ID,
		arg.Name,
		arg.ProviderType,
		arg.ApiKeyEncrypted,
		arg.BaseUrl,
		arg.Model,
		arg.Config,
	)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ProviderType,
		&i.ApiKeyEncrypted,
		&i.BaseUrl,
		&i.Model,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
