// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (
    owner_id,
    agent_id,
    content,
    memory_type,
    parent_id,
    tags,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING id, owner_id, agent_id, content, memory_type, parent_id, tags, metadata, created_at, updated_at
`

type CreateMemoryParams struct {
	OwnerID    pgtype.UUID `json:"owner_id"`
	AgentID    pgtype.UUID `json:"agent_id"`
	Content    string      `json:"content"`
	MemoryType string      `json:"memory_type"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Tags       []string    `json:"tags"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.OwnerID,
		arg.AgentID,
		arg.Content,
		arg.MemoryType,
		arg.ParentID,
		arg.Tags,
		arg.Metadata,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AgentID,
		&i.Content,
		&i.MemoryType,
		&i.ParentID,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories WHERE id = $1
`

func (q *Queries) DeleteMemory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMemory, id)
	return err
}

const getMemoryByID = `-- name: GetMemoryByID :one
SELECT id, owner_id, agent_id, content, memory_type, parent_id, tags, metadata, created_at, updated_at FROM memories WHERE id = $1
`

func (q *Queries) GetMemoryByID(ctx context.Context, id pgtype.UUID) (Memory, error) {
	row := q.db.QueryRow(ctx, getMemoryByID, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AgentID,
		&i.Content,
		&i.MemoryType,
		&i.ParentID,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemoriesByAgent = `-- name: ListMemoriesByAgent :many
SELECT id, owner_id, agent_id, content, memory_type, parent_id, tags, metadata, created_at, updated_at FROM memories 
WHERE owner_id = $1 AND agent_id = $2
ORDER BY created_at DESC 
LIMIT $3 OFFSET $4
`

type ListMemoriesByAgentParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	AgentID pgtype.UUID `json:"agent_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListMemoriesByAgent(ctx context.Context, arg ListMemoriesByAgentParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listMemoriesByAgent,
		arg.OwnerID,
		arg.AgentID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AgentID,
			&i.Content,
			&i.MemoryType,
			&i.ParentID,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesByOwner = `-- name: ListMemoriesByOwner :many
SELECT id, owner_id, agent_id, content, memory_type, parent_id, tags, metadata, created_at, updated_at FROM memories 
WHERE owner_id = $1 
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type ListMemoriesByOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListMemoriesByOwner(ctx context.Context, arg ListMemoriesByOwnerParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listMemoriesByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AgentID,
			&i.Content,
			&i.MemoryType,
			&i.ParentID,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesByType = `-- name: ListMemoriesByType :many
SELECT id, owner_id, agent_id, content, memory_type, parent_id, tags, metadata, created_at, updated_at FROM memories 
WHERE owner_id = $1 AND memory_type = $2
ORDER BY created_at DESC 
LIMIT $3 OFFSET $4
`

type ListMemoriesByTypeParams struct {
	OwnerID    pgtype.UUID `json:"owner_id"`
	MemoryType string      `json:"memory_type"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListMemoriesByType(ctx context.Context, arg ListMemoriesByTypeParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listMemoriesByType,
		arg.OwnerID,
		arg.MemoryType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AgentID,
			&i.Content,
			&i.MemoryType,
			&i.ParentID,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemories = `-- name: SearchMemories :many
SELECT id, owner_id, agent_id, content, memory_type, parent_id, tags, metadata, created_at, updated_at FROM memories 
WHERE owner_id = $1 AND (
    content ILIKE '%' || $2 || '%' OR
    $2 = ANY(tags)
)
ORDER BY created_at DESC 
LIMIT $3 OFFSET $4
`

type SearchMemoriesParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Column2 pgtype.Text `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchMemories(ctx context.Context, arg SearchMemoriesParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, searchMemories,
		arg.OwnerID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AgentID,
			&i.Content,
			&i.MemoryType,
			&i.ParentID,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemory = `-- name: UpdateMemory :one
UPDATE memories SET
    content = $2,
    memory_type = $3,
    parent_id = $4,
    tags = $5,
    metadata = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, agent_id, content, memory_type, parent_id, tags, metadata, created_at, updated_at
`

type UpdateMemoryParams struct {
	ID         pgtype.UUID `json:"id"`
	Content    string      `json:"content"`
	MemoryType string      `json:"memory_type"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Tags       []string    `json:"tags"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, updateMemory,
		arg.ID,
		arg.Content,
		arg.MemoryType,
		arg.ParentID,
		arg.Tags,
		arg.Metadata,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AgentID,
		&i.Content,
		&i.MemoryType,
		&i.ParentID,
		&i.Tags,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
