// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID          pgtype.UUID      `json:"id"`
	OwnerID     pgtype.UUID      `json:"owner_id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Config      []byte           `json:"config"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type AgentSetting struct {
	ID        pgtype.UUID      `json:"id"`
	AgentID   pgtype.UUID      `json:"agent_id"`
	Key       string           `json:"key"`
	Value     pgtype.Text      `json:"value"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type AgentToolWhitelist struct {
	ID        pgtype.UUID      `json:"id"`
	AgentID   pgtype.UUID      `json:"agent_id"`
	ToolName  string           `json:"tool_name"`
	Enabled   bool             `json:"enabled"`
	Config    []byte           `json:"config"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type LlmAttachment struct {
	ID         pgtype.UUID      `json:"id"`
	AgentID    pgtype.UUID      `json:"agent_id"`
	ProviderID pgtype.UUID      `json:"provider_id"`
	Layer      string           `json:"layer"`
	Priority   int32            `json:"priority"`
	Config     []byte           `json:"config"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type LlmProvider struct {
	ID              pgtype.UUID      `json:"id"`
	OwnerID         pgtype.UUID      `json:"owner_id"`
	Name            string           `json:"name"`
	ProviderType    string           `json:"provider_type"`
	ApiKeyEncrypted pgtype.Text      `json:"api_key_encrypted"`
	BaseUrl         pgtype.Text      `json:"base_url"`
	Model           pgtype.Text      `json:"model"`
	Config          []byte           `json:"config"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Memory struct {
	ID         pgtype.UUID      `json:"id"`
	OwnerID    pgtype.UUID      `json:"owner_id"`
	AgentID    pgtype.UUID      `json:"agent_id"`
	Content    string           `json:"content"`
	MemoryType string           `json:"memory_type"`
	ParentID   pgtype.UUID      `json:"parent_id"`
	Tags       []string         `json:"tags"`
	Metadata   []byte           `json:"metadata"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID      `json:"id"`
	AgentID   pgtype.UUID      `json:"agent_id"`
	OwnerID   pgtype.UUID      `json:"owner_id"`
	Status    string           `json:"status"`
	StartedAt pgtype.Timestamp `json:"started_at"`
	EndedAt   pgtype.Timestamp `json:"ended_at"`
	Metadata  []byte           `json:"metadata"`
}

type SystemSetting struct {
	ID        pgtype.UUID      `json:"id"`
	Key       string           `json:"key"`
	Value     string           `json:"value"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Thought struct {
	ID        pgtype.UUID      `json:"id"`
	SessionID pgtype.UUID      `json:"session_id"`
	Layer     string           `json:"layer"`
	Content   string           `json:"content"`
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Email        string           `json:"email"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
