// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    agent_id,
    owner_id,
    status,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, agent_id, owner_id, status, started_at, ended_at, metadata
`

type CreateSessionParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	OwnerID  pgtype.UUID `json:"owner_id"`
	Status   string      `json:"status"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AgentID,
		arg.OwnerID,
		arg.Status,
		arg.Metadata,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OwnerID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.Metadata,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const endSession = `-- name: EndSession :one
UPDATE sessions SET
    status = $2,
    ended_at = NOW()
WHERE id = $1
RETURNING id, agent_id, owner_id, status, started_at, ended_at, metadata
`

type EndSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, endSession, arg.ID, arg.Status)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OwnerID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.Metadata,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, agent_id, owner_id, status, started_at, ended_at, metadata FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OwnerID,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.Metadata,
	)
	return i, err
}

const listSessionsByAgent = `-- name: ListSessionsByAgent :many
SELECT id, agent_id, owner_id, status, started_at, ended_at, metadata FROM sessions 
WHERE agent_id = $1 
ORDER BY started_at DESC 
LIMIT $2 OFFSET $3
`

type ListSessionsByAgentParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListSessionsByAgent(ctx context.Context, arg ListSessionsByAgentParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByAgent, arg.AgentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.OwnerID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByOwner = `-- name: ListSessionsByOwner :many
SELECT id, agent_id, owner_id, status, started_at, ended_at, metadata FROM sessions 
WHERE owner_id = $1 
ORDER BY started_at DESC 
LIMIT $2 OFFSET $3
`

type ListSessionsByOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListSessionsByOwner(ctx context.Context, arg ListSessionsByOwnerParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.OwnerID,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
