// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAgentSetting = `-- name: DeleteAgentSetting :exec
DELETE FROM agent_settings WHERE agent_id = $1 AND key = $2
`

type DeleteAgentSettingParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Key     string      `json:"key"`
}

func (q *Queries) DeleteAgentSetting(ctx context.Context, arg DeleteAgentSettingParams) error {
	_, err := q.db.Exec(ctx, deleteAgentSetting, arg.AgentID, arg.Key)
	return err
}

const deleteSystemSetting = `-- name: DeleteSystemSetting :exec
DELETE FROM system_settings WHERE key = $1
`

func (q *Queries) DeleteSystemSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSystemSetting, key)
	return err
}

const getAgentSetting = `-- name: GetAgentSetting :one
SELECT id, agent_id, key, value, created_at, updated_at FROM agent_settings WHERE agent_id = $1 AND key = $2
`

type GetAgentSettingParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Key     string      `json:"key"`
}

func (q *Queries) GetAgentSetting(ctx context.Context, arg GetAgentSettingParams) (AgentSetting, error) {
	row := q.db.QueryRow(ctx, getAgentSetting, arg.AgentID, arg.Key)
	var i AgentSetting
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT id, key, value, created_at, updated_at FROM system_settings WHERE key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentSettings = `-- name: ListAgentSettings :many
SELECT id, agent_id, key, value, created_at, updated_at FROM agent_settings WHERE agent_id = $1
`

func (q *Queries) ListAgentSettings(ctx context.Context, agentID pgtype.UUID) ([]AgentSetting, error) {
	rows, err := q.db.Query(ctx, listAgentSettings, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSetting
	for rows.Next() {
		var i AgentSetting
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT id, key, value, created_at, updated_at FROM system_settings
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentSetting = `-- name: UpsertAgentSetting :one
INSERT INTO agent_settings (agent_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (agent_id, key) 
DO UPDATE SET value = $3, updated_at = NOW()
RETURNING id, agent_id, key, value, created_at, updated_at
`

type UpsertAgentSettingParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Key     string      `json:"key"`
	Value   pgtype.Text `json:"value"`
}

func (q *Queries) UpsertAgentSetting(ctx context.Context, arg UpsertAgentSettingParams) (AgentSetting, error) {
	row := q.db.QueryRow(ctx, upsertAgentSetting, arg.AgentID, arg.Key, arg.Value)
	var i AgentSetting
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) 
DO UPDATE SET value = $2, updated_at = NOW()
RETURNING id, key, value, created_at, updated_at
`

type UpsertSystemSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting, arg.Key, arg.Value)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
