// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: thoughts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createThought = `-- name: CreateThought :one
INSERT INTO thoughts (
    session_id,
    layer,
    content,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, session_id, layer, content, metadata, created_at
`

type CreateThoughtParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Layer     string      `json:"layer"`
	Content   string      `json:"content"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateThought(ctx context.Context, arg CreateThoughtParams) (Thought, error) {
	row := q.db.QueryRow(ctx, createThought,
		arg.SessionID,
		arg.Layer,
		arg.Content,
		arg.Metadata,
	)
	var i Thought
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Layer,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteThought = `-- name: DeleteThought :exec
DELETE FROM thoughts WHERE id = $1
`

func (q *Queries) DeleteThought(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteThought, id)
	return err
}

const getThoughtByID = `-- name: GetThoughtByID :one
SELECT id, session_id, layer, content, metadata, created_at FROM thoughts WHERE id = $1
`

func (q *Queries) GetThoughtByID(ctx context.Context, id pgtype.UUID) (Thought, error) {
	row := q.db.QueryRow(ctx, getThoughtByID, id)
	var i Thought
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Layer,
		&i.Content,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listThoughtsByLayer = `-- name: ListThoughtsByLayer :many
SELECT id, session_id, layer, content, metadata, created_at FROM thoughts 
WHERE session_id = $1 AND layer = $2
ORDER BY created_at ASC 
LIMIT $3 OFFSET $4
`

type ListThoughtsByLayerParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Layer     string      `json:"layer"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListThoughtsByLayer(ctx context.Context, arg ListThoughtsByLayerParams) ([]Thought, error) {
	rows, err := q.db.Query(ctx, listThoughtsByLayer,
		arg.SessionID,
		arg.Layer,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thought
	for rows.Next() {
		var i Thought
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Layer,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThoughtsBySession = `-- name: ListThoughtsBySession :many
SELECT id, session_id, layer, content, metadata, created_at FROM thoughts 
WHERE session_id = $1 
ORDER BY created_at ASC 
LIMIT $2 OFFSET $3
`

type ListThoughtsBySessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListThoughtsBySession(ctx context.Context, arg ListThoughtsBySessionParams) ([]Thought, error) {
	rows, err := q.db.Query(ctx, listThoughtsBySession, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thought
	for rows.Next() {
		var i Thought
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Layer,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
