// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tool_whitelists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteToolWhitelist = `-- name: DeleteToolWhitelist :exec
DELETE FROM agent_tool_whitelists WHERE agent_id = $1 AND tool_name = $2
`

type DeleteToolWhitelistParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	ToolName string      `json:"tool_name"`
}

func (q *Queries) DeleteToolWhitelist(ctx context.Context, arg DeleteToolWhitelistParams) error {
	_, err := q.db.Exec(ctx, deleteToolWhitelist, arg.AgentID, arg.ToolName)
	return err
}

const getToolWhitelist = `-- name: GetToolWhitelist :one
SELECT id, agent_id, tool_name, enabled, config, created_at, updated_at FROM agent_tool_whitelists WHERE agent_id = $1 AND tool_name = $2
`

type GetToolWhitelistParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	ToolName string      `json:"tool_name"`
}

func (q *Queries) GetToolWhitelist(ctx context.Context, arg GetToolWhitelistParams) (AgentToolWhitelist, error) {
	row := q.db.QueryRow(ctx, getToolWhitelist, arg.AgentID, arg.ToolName)
	var i AgentToolWhitelist
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ToolName,
		&i.Enabled,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listToolWhitelists = `-- name: ListToolWhitelists :many
SELECT id, agent_id, tool_name, enabled, config, created_at, updated_at FROM agent_tool_whitelists WHERE agent_id = $1
`

func (q *Queries) ListToolWhitelists(ctx context.Context, agentID pgtype.UUID) ([]AgentToolWhitelist, error) {
	rows, err := q.db.Query(ctx, listToolWhitelists, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentToolWhitelist
	for rows.Next() {
		var i AgentToolWhitelist
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ToolName,
			&i.Enabled,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertToolWhitelist = `-- name: UpsertToolWhitelist :one
INSERT INTO agent_tool_whitelists (agent_id, tool_name, enabled, config)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id, tool_name) 
DO UPDATE SET enabled = $3, config = $4, updated_at = NOW()
RETURNING id, agent_id, tool_name, enabled, config, created_at, updated_at
`

type UpsertToolWhitelistParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	ToolName string      `json:"tool_name"`
	Enabled  bool        `json:"enabled"`
	Config   []byte      `json:"config"`
}

func (q *Queries) UpsertToolWhitelist(ctx context.Context, arg UpsertToolWhitelistParams) (AgentToolWhitelist, error) {
	row := q.db.QueryRow(ctx, upsertToolWhitelist,
		arg.AgentID,
		arg.ToolName,
		arg.Enabled,
		arg.Config,
	)
	var i AgentToolWhitelist
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ToolName,
		&i.Enabled,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
