#!/bin/bash

# VARIABLES
ACE_LOGGER_VERBOSE_ENV="."


# STARTUP
run_tests() {
    echo "Installing/Updating test dependencies..."
    pip install --upgrade -r tests/requirements

    python -m pytest tests/unit/ -v
    exit $?
}

run_ace() {
    cd app || exit

    echo "Installing/Updating requirements..."
    pip install --upgrade -r requirements

    ACE_LOGGER_FILE_NAME="startup" ACE_LOGGER_VERBOSE="$ACE_LOGGER_VERBOSE_ENV" ./startup.py "${@}"
    deactivate
    exit $?
}

# MAIN
main() {
    # Store original arguments
    original_args=("$@")
    
    # Initialize variables
    run_tests=false

    # Process arguments for environment variables
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dev)
                ACE_LOGGER_VERBOSE_ENV=""
                ;;
            --test)
                run_tests=true
                ;;
        esac
        shift
    done

    if [ ! -d ".venv" ]; then
        echo "Python virtual environment doesn't exist, creating one..."
        python3.13 -m venv .venv
    fi
    source .venv/bin/activate

    if [ "$run_tests" = true ]; then
        run_tests
    fi

    # Use original arguments when running ace
    run_ace "${original_args[@]}"
}

trap 'exit $?' ERR

main "$@"