apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ ace_pod_name }}
  name: {{ ace_pod_name }}
spec:
  containers:
  - command:
    - {{ start_command }}
    - --{{ controller_name }}
    image: {{ ace_image_name }}
    name: {{ controller_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ controller_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ controller_port }}
      hostPort: {{ controller_port }}
    volumeMounts:
    - mountPath: {{ controller_container_path }}
      name: {{ controller_volume }}
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  - command:
    - {{ start_command }}
    - --{{ queue_name }}
    image: {{ ace_image_name }}
    name: {{ queue_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ queue_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ queue_port }}
    volumeMounts:
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  - command:
    - {{ start_command }}
    - --{{ model_provider_name }}
    image: {{ ace_image_name }}
    name: {{ model_provider_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ model_provider_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ model_provider_port }}
    volumeMounts:
    - mountPath: {{ model_provider_container_path }}
      name: {{ model_provider_volume }}
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  - command:
    - {{ start_command }}
    - --{{ telemetry_name }}
    image: {{ ace_image_name }}
    name: {{ telemetry_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ telemetry_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ telemetry_port }}
    volumeMounts:
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  - command:
    - {{ start_command }}
    - --{{ actions_name }}
    image: {{ ace_image_name }}
    name: {{ actions_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ actions_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ actions_port }}
    volumeMounts:
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  - command:
    - {{ start_command }}
    - --{{ memory_name }}
    image: {{ ace_image_name }}
    name: {{ memory_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ memory_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ memory_port }}
    volumeMounts:
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  - command:
    - {{ start_command }}
    - --{{ aspirational_name }}
    image: {{ ace_image_name }}
    name: {{ aspirational_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ aspirational_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ aspirational_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  - command:
    - {{ start_command }}
    - --{{ global_strategy_name }}
    image: {{ ace_image_name }}
    name: {{ global_strategy_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ global_strategy_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ global_strategy_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  - command:
    - {{ start_command }}
    - --{{ agent_model_name }}
    image: {{ ace_image_name }}
    name: {{ agent_model_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ agent_model_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ agent_model_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  - command:
    - {{ start_command }}
    - --{{ executive_function_name }}
    image: {{ ace_image_name }}
    name: {{ executive_function_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ executive_function_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ executive_function_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  - command:
    - {{ start_command }}
    - --{{ cognitive_control_name }}
    image: {{ ace_image_name }}
    name: {{ cognitive_control_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ cognitive_control_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ cognitive_control_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  - command:
    - {{ start_command }}
    - --{{ task_prosecution_name }}
    image: {{ ace_image_name }}
    name: {{ task_prosecution_name }}
    env:
    - name: {{ logger_name_env }}
      value: {{ task_prosecution_name }}
    - name: {{ logger_verbose_env }}
      value: {{ dev_env }}
    ports:
    - containerPort: {{ task_prosecution_port }}
    volumeMounts:
    - mountPath: {{ layers_container_path }}
      name: {{ layers_volume }}
    - mountPath: {{ output_container_path }}
      name: {{ output_volume }}
    - mountPath: {{ logs_container_path }}
      name: {{ logs_volume }}
  volumes:
  - hostPath:
      path: {{ logs_host_path }}
      type: Directory
    name: {{ logs_volume }}
  - hostPath:
      path: {{ controller_host_path }}
      type: Directory
    name: {{ controller_volume }}
  - hostPath:
      path: {{ layers_host_path }}
      type: Directory
    name: {{ layers_volume }}
  - hostPath:
      path: {{ model_provider_host_path }}
      type: Directory
    name: {{ model_provider_volume }}
  - hostPath:
      path: {{ output_host_path }}
      type: Directory
    name: {{ output_volume }}
