package main

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"

	"github.com/jackc/pgx/v5"
)

func generateOpenAPI(ctx context.Context, _ *pgx.Conn, repoRoot string) error {
	// Fetch the OpenAPI spec from the running API server (generated by Annot8)
	apiURL := os.Getenv("API_URL")
	if apiURL == "" {
		apiURL = "http://127.0.0.1:8080"
	}

	resp, err := http.Get(apiURL + "/openapi.json")
	if err != nil {
		return fmt.Errorf("fetching OpenAPI spec from %s: %w", apiURL, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("API returned status %d for /openapi.json", resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("reading OpenAPI response: %w", err)
	}

	outputDir := filepath.Join(repoRoot, "documentation/api")
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}

	filePath := filepath.Join(outputDir, "openapi.json")
	content := "// Auto-generated by Annot8 — do not edit manually\n// Source: " + apiURL + "/openapi.json\n// Run 'make test' to regenerate\n\n" + string(body)
	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", filePath, err)
	}

	fmt.Printf("Generated: %s (%d bytes)\n", filePath, len(body))
	return nil
}
