name: Run Tests
on:
  pull_request:
    branches:
      - main # Run on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
        
      - name: Run tests
        id: run_tests
        run: ./ace --test
        
      - name: Upload test results
        if: always() # Run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: |
            .pytest_cache/
            tests/**/test-*.xml
            tests/**/test-*.html
          
      # Force the workflow to fail if tests failed
      - name: Check test results
        if: steps.run_tests.outcome != 'success'
        run: exit 1
