name: Run Tests

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    branches:
      - main  # Run on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          
      - name: Make ace executable
        run: chmod +x ./ace
        
      - name: Run tests
        run: ./ace --test

      - name: Upload test results
        if: always()  # Run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: |
            .pytest_cache/
            tests/**/test-*.xml
            tests/**/test-*.html